#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# SETUP
./Allrun.pre

# SERIAL
overPimpleDyMFoam > log.overPimpleDyMFoam

# PARALLEL
# runApplication decomposePar -cellDist
# runParallel $(getApplication)
# runApplication reconstructPar

#------------------------------------------------------------------------------
